dbt_script:
  outputs:
    dev:
      dataset: jcdeol03_finalproject_dimasadihartomo
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/keys/credential.json
      location: US
      method: service-account
      priority: interactive
      project: purwadika
      threads: 4
      type: bigquery
  target: dev
